import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { LayoutDashboard, Sparkles, GraduationCap, Images, Video, MessageSquare, CalendarDays, Settings as SettingsIcon, LogOut, ExternalLink, Plus, Search, Pencil, Eye, EyeOff, Trash2, Menu, X, Check, Upload, LockKeyhole, RefreshCw, Phone } from 'lucide-react';
import { api, errorMessage, setCsrf } from './api';
import { Brand, Empty, ErrorBox, Icon, Modal } from './components';
import type { Content, Enquiry, Kind, Session, Settings } from './types';

type Tab='overview'|'enquiries'|'settings'|'account'|Kind;
const sections: {id:Tab;label:string;icon:typeof Sparkles}[] = [
  {id:'overview',label:'Overview',icon:LayoutDashboard},{id:'services',label:'Services',icon:Sparkles},
  {id:'courses',label:'Academy',icon:GraduationCap},{id:'gallery',label:'Gallery',icon:Images},
  {id:'tiktok',label:'TikTok videos',icon:Video},{id:'testimonials',label:'Testimonials',icon:MessageSquare},
  {id:'enquiries',label:'Enquiries',icon:CalendarDays},{id:'settings',label:'Studio settings',icon:SettingsIcon},
];
const labels:Record<Kind,string>={services:'service',courses:'course',gallery:'photo',tiktok:'video',testimonials:'review'};
const defaults:Record<Kind,Partial<Content>>={
  services:{title:'',description:'',category:'Makeup',icon:'sparkles',price:'',duration:'',image:''},
  courses:{title:'',description:'',duration:''},gallery:{title:'',image:'',category:'Bridal',alt:''},
  tiktok:{title:'',url:''},testimonials:{title:'',quote:'',service:'',rating:5},
};
export default function Admin() {
  const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true),[tab,setTab]=useState<Tab>('overview'),[nav,setNav]=useState(false),[logoutError,setLogoutError]=useState('');
  useEffect(()=>{document.title='Studio Admin | Choose Me';api<Session>('/admin/session').then(s=>{setCsrf(s.csrf);setSession(s);}).catch(()=>{}).finally(()=>setChecking(false));const expire=()=>{setCsrf('');setSession(null);};window.addEventListener('session-expired',expire);return()=>window.removeEventListener('session-expired',expire);},[]);
  async function logout(){try{await api('/admin/logout',{method:'POST'});setCsrf('');setSession(null);}catch(e){setLogoutError(errorMessage(e));}}
  if(checking)return <div className="page-loading"><Brand/><p>Opening your studio…</p></div>;
  if(!session)return <Login onLogin={s=>{setCsrf(s.csrf);setSession(s);}}/>;
  function changeTab(value:Tab){setTab(value);setNav(false);window.scrollTo(0,0);}
  return <div className="admin-shell"><aside className={`admin-sidebar ${nav?'is-open':''}`}><div className="admin-brand"><Brand/><button className="icon-button mobile-menu" aria-label="Close navigation" onClick={()=>setNav(false)}><X/></button></div><div className="sidebar-label">YOUR STUDIO</div><nav aria-label="Admin navigation">{sections.map(({id,label,icon:C})=><button key={id} className={tab===id?'active':''} onClick={()=>changeTab(id)} aria-current={tab===id?'page':undefined}><C size={19}/>{label}{id==='enquiries'&&<span className="nav-small">Inbox</span>}</button>)}</nav><div className="sidebar-bottom"><a href="/" target="_blank" rel="noreferrer"><ExternalLink size={18}/> View website</a><button onClick={()=>changeTab('account')}><LockKeyhole size={18}/> Account & password</button><button onClick={logout}><LogOut size={18}/> Sign out</button><div className="admin-person"><span>R</span><div>Studio administrator<small>{session.email}</small></div></div></div></aside>{nav&&<button className="sidebar-overlay" aria-label="Close navigation" onClick={()=>setNav(false)}/>}
    <div className="admin-content"><header className="admin-topbar"><div><button className="icon-button mobile-menu" aria-label="Open admin navigation" onClick={()=>setNav(true)}><Menu/></button><span>Choose Me <span className="breadcrumb">/</span> <strong>{tab==='account'?'Account':sections.find(s=>s.id===tab)?.label}</strong></span></div><a href="/" target="_blank" rel="noreferrer">View live site <ExternalLink size={15}/></a></header><main className="admin-main"><ErrorBox message={logoutError}/>{tab==='overview'?<Overview navigate={changeTab}/>:tab==='enquiries'?<Enquiries/>:tab==='settings'?<SettingsPage/>:tab==='account'?<Account/>:<ContentManager key={tab} kind={tab}/>}</main><footer className="admin-footer">Choose Me Makeup Studio & Academy <span>Made for your studio.</span></footer></div></div>;
}
function Login({onLogin}:{onLogin:(session:Session)=>void}) {
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{onLogin(await api<Session>('/login',{method:'POST',body:JSON.stringify({email:form.get('email'),password:form.get('password')})}));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <main className="login-page"><div className="login-art"><img src="/images/still-life.webp" alt="Makeup brushes and rose blush"/><div><Brand light/><h1>A beautiful space.<br/><em>Your studio.</em></h1></div></div><div className="login-form"><Brand/><span className="eyebrow">STUDIO ADMINISTRATION</span><h1>Welcome back.</h1><p>A little care for the business behind the beauty.</p><form onSubmit={submit} className="form-stack"><label>Email address<input name="email" type="email" required autoComplete="username" maxLength={254}/></label><label>Password<input name="password" type="password" required autoComplete="current-password" maxLength={200}/></label><ErrorBox message={error}/><button className="button" disabled={busy}>{busy?'Signing in…':'Sign in to your studio'}</button></form><a className="text-link" href="/">Return to the website</a></div></main>;
}
function PageHeading({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:ReactNode}) {return <div className="admin-page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{children}</div>;}
type OverviewData={services:number;visibleServices:number;enquiries:number;newEnquiries:number;gallery:number;recent:Enquiry[]};
function Overview({navigate}:{navigate:(tab:Tab)=>void}) {
  const [data,setData]=useState<OverviewData|null>(null),[error,setError]=useState('');
  useEffect(()=>{api<OverviewData>('/admin/overview').then(setData).catch(e=>setError(errorMessage(e)));},[]);
  return <><PageHeading eyebrow="YOUR STUDIO, AT A GLANCE" title="Hello, beautiful business." description="A little overview of what’s happening at Choose Me."><button className="button" onClick={()=>navigate('services')}><Plus size={17}/> Manage services</button></PageHeading><ErrorBox message={error}/>{data?<><div className="stats-grid">{[{label:'Published services',value:data.visibleServices,note:`${data.services} services in your collection`,icon:Sparkles,tab:'services'},{label:'New enquiries',value:data.newEnquiries,note:'Ready for a personal reply',icon:CalendarDays,tab:'enquiries'},{label:'Portfolio photos',value:data.gallery,note:'Your studio’s beautiful work',icon:Images,tab:'gallery'}].map(({label,value,note,icon:C,tab})=><button className="stat-card" key={label} onClick={()=>navigate(tab as Tab)}><div>{label}<C size={21}/></div><strong>{value}</strong><span>{note}</span></button>)}</div><div className="dashboard-grid"><section className="admin-panel"><div className="panel-heading"><h2>Latest enquiries</h2><button className="text-link" onClick={()=>navigate('enquiries')}>View all</button></div>{data.recent.length?data.recent.map(x=><div className="recent-enquiry" key={x.id}><div className="person-avatar">{x.name[0]}</div><div><strong>{x.name}</strong><span>{x.subject}</span></div><span className={`status-badge status-${x.status}`}>{x.status}</span></div>):<Empty title="A little quiet, for now" description="New appointment and course enquiries will arrive here."/>}</section><section className="admin-panel quick-actions"><div className="panel-heading"><h2>Make it yours</h2></div><p>Keep your website as fresh as your latest looks.</p><button onClick={()=>navigate('gallery')}><Images size={21}/><span>Add your studio photos<small>Show the details you’re proud of.</small></span><Plus size={18}/></button><button onClick={()=>navigate('tiktok')}><Video size={21}/><span>Share a TikTok look<small>Just paste a video link.</small></span><Plus size={18}/></button><button onClick={()=>navigate('settings')}><SettingsIcon size={21}/><span>Update studio details<small>Contacts, images and your story.</small></span><Pencil size={17}/></button></section></div><div className="admin-tip"><EyeOff size={22}/><div><strong>Taking a service off the menu for a while?</strong><p>Hide it to keep its details for later. You can publish it again whenever you’re ready.</p></div></div></>:!error&&<p className="loading-copy">Loading your studio overview…</p>}</>;
}
function ContentManager({kind}:{kind:Kind}) {
  const [items,setItems]=useState<Content[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[editing,setEditing]=useState<Content|null>(null),[deleting,setDeleting]=useState<Content|null>(null),[busy,setBusy]=useState('');
  async function load(){try{setItems(await api<Content[]>(`/admin/content/${kind}`));}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
  useEffect(()=>{void load();},[kind]);
  const name=labels[kind];
  async function visibility(item:Content){setBusy(item.id);setError('');try{await api(`/admin/content/${kind}/${item.id}/visibility`,{method:'PATCH',body:JSON.stringify({visible:!item.visible})});setItems(v=>v.map(x=>x.id===item.id?{...x,visible:!x.visible}:x));setNotice(`${item.title} is now ${item.visible?'hidden from':'published on'} your website.`);}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
  async function remove(){if(!deleting)return;setBusy(deleting.id);setError('');try{await api(`/admin/content/${kind}/${deleting.id}`,{method:'DELETE'});setItems(v=>v.filter(x=>x.id!==deleting.id));setNotice(`${deleting.title} was deleted.`);setDeleting(null);}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
  const visible=items.filter(x=>x.title.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||x.visible===(filter==='visible')));
  const title={services:'Your beauty menu.',courses:'Grow your academy.',gallery:'Your work, beautifully shown.',tiktok:'A little motion. A lot of beauty.',testimonials:'Kind words, kept close.'}[kind];
  return <><PageHeading eyebrow="YOUR WEBSITE CONTENT" title={title} description={`Add, edit, hide or permanently delete a ${name}. Published changes appear on your website.`}><button className="button" onClick={()=>setEditing({id:'',visible:true,order:items.length+1,...defaults[kind]} as Content)}><Plus size={18}/> Add {name}</button></PageHeading><ErrorBox message={error}/>{notice&&<div className="notice" role="status"><Check size={16}/>{notice}<button className="icon-button" onClick={()=>setNotice('')} aria-label="Dismiss notice"><X size={16}/></button></div>}
    <div className="content-toolbar"><label className="search-input"><Search size={18}/><input aria-label={`Search ${kind}`} placeholder={`Search ${kind}…`} value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="admin-filter">{['all','visible','hidden'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x==='all'?`All (${items.length})`:x==='visible'?'Published':'Hidden'}</button>)}</div></div>
    {loading?<p className="loading-copy">Loading your {kind}…</p>:visible.length?<div className="content-table"><div className="table-head"><span>{kind==='testimonials'?'Client':name}</span><span>Category / details</span><span>Visibility</span><span>Actions</span></div>{visible.map(item=><div className="content-row" key={item.id}><div className="content-title">{item.image?<img src={item.image} alt=""/>:<span className="content-icon"><Icon name={item.icon}/></span>}<div><strong>{item.title}</strong><small>{item.description||item.quote||item.url||item.alt}</small></div></div><span className="content-category">{item.category||item.service||item.duration||(kind==='tiktok'?'TikTok':'—')}<small>{item.price}</small></span><span className={`status-badge ${item.visible?'published':'hidden'}`}>{item.visible?'Published':'Hidden'}</span><div className="row-actions"><button className="icon-button" aria-label={`Edit ${item.title}`} title="Edit" onClick={()=>setEditing(item)} disabled={busy===item.id}><Pencil size={17}/></button><button className="icon-button" aria-label={`${item.visible?'Hide':'Publish'} ${item.title}`} title={item.visible?'Hide from website':'Publish on website'} onClick={()=>visibility(item)} disabled={busy===item.id}>{item.visible?<EyeOff size={18}/>:<Eye size={18}/>}</button><button className="icon-button danger-icon" aria-label={`Delete ${item.title}`} title="Permanently delete" onClick={()=>setDeleting(item)} disabled={busy===item.id}><Trash2 size={17}/></button></div></div>)}</div>:<Empty title={search||filter!=='all'?'No matching items':`Your first ${name} starts here`} description={search||filter!=='all'?'Try another search or visibility filter.':`Add a ${name} and make your studio’s website your own.`}/>}<p className="table-footnote">{items.filter(x=>x.visible).length} published · {items.filter(x=>!x.visible).length} hidden · Hidden items stay saved in your admin.</p>
    {editing&&<ContentEditor kind={kind} item={editing} onClose={()=>setEditing(null)} onSave={item=>{setItems(old=>[...old.filter(x=>x.id!==item.id),item].sort((a,b)=>a.order-b.order));setEditing(null);setNotice(`${item.title} has been saved.`);}}/>}
    {deleting&&<Modal title={`Delete this ${name}?`} onClose={()=>setDeleting(null)}><p><strong>{deleting.title}</strong> will be permanently removed. To take it off the website temporarily, use Hide instead.</p><ErrorBox message={error}/><div className="modal-actions"><button className="button button-outline" onClick={()=>setDeleting(null)}>Keep {name}</button><button className="button button-danger" disabled={!!busy} onClick={remove}>{busy?'Deleting…':'Delete permanently'}</button></div></Modal>}
  </>;
}
function ImageField({label,value,onChange,onBusy}:{label:string;value:string;onChange:(value:string)=>void;onBusy:(busy:boolean)=>void}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  async function upload(file?:File){if(!file)return;setBusy(true);onBusy(true);setError('');const form=new FormData();form.append('image',file);try{const data=await api<{url:string}>('/admin/upload',{method:'POST',body:form});onChange(data.url);}catch(e){setError(errorMessage(e));}finally{setBusy(false);onBusy(false);}}
  return <div className="image-field"><span className="field-label">{label}</span><div className="image-field-content">{value&&<img src={value} alt="Selected image preview"/>}<div><label className="upload-button"><Upload size={17}/>{busy?'Uploading…':'Upload a photo'}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={busy} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label><small>JPG, PNG, WebP or AVIF · up to 8 MB</small></div></div><input aria-label={`${label} URL`} placeholder="Or paste an HTTPS image URL" value={value} onChange={e=>onChange(e.target.value)}/><ErrorBox message={error}/></div>;
}
function ContentEditor({kind,item,onClose,onSave}:{kind:Kind;item:Content;onClose:()=>void;onSave:(item:Content)=>void}) {
  const [draft,setDraft]=useState({...item}),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
  const update=(key:keyof Content,value:unknown)=>setDraft(old=>({...old,[key]:value}));
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const saved=await api<Content>(`/admin/content/${kind}${item.id?`/${item.id}`:''}`,{method:item.id?'PUT':'POST',body:JSON.stringify(draft)});onSave(saved);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <Modal title={`${item.id?'Edit':'Add'} ${labels[kind]}`} onClose={()=>{if(!busy&&!uploading)onClose();}}><form className="form-stack" onSubmit={submit}><label>{kind==='testimonials'?'Client name':'Title'}<input required maxLength={160} value={draft.title} onChange={e=>update('title',e.target.value)}/></label>
    {['services','courses'].includes(kind)&&<label>Description<textarea required rows={3} maxLength={kind==='services'?1200:1500} value={draft.description} onChange={e=>update('description',e.target.value)}/></label>}
    {(kind==='services'||kind==='gallery')&&<label>Category<select value={draft.category} onChange={e=>update('category',e.target.value)}>{(kind==='services'?['Makeup','Hair','Nails','Skin','Mehendi']:['Bridal','Makeup','Hair','Nails','Mehendi','Skin']).map(x=><option key={x}>{x}</option>)}</select></label>}
    {kind==='services'&&<><div className="form-row"><label>Price label <span className="optional">(optional)</span><input placeholder="e.g. From NPR 1,500" maxLength={100} value={draft.price} onChange={e=>update('price',e.target.value)}/></label><label>Icon<select value={draft.icon} onChange={e=>update('icon',e.target.value)}>{['sparkles','scissors','flower','leaf','brush'].map(x=><option key={x}>{x}</option>)}</select></label></div></>}
    {['services','courses'].includes(kind)&&<label>Duration <span className="optional">(optional)</span><input placeholder="e.g. 60 minutes" maxLength={100} value={draft.duration} onChange={e=>update('duration',e.target.value)}/></label>}
    {(kind==='gallery'||kind==='services')&&<ImageField label={kind==='services'?'Service image (optional)':'Portfolio photo'} value={draft.image||''} onChange={v=>update('image',v)} onBusy={setUploading}/>}
    {kind==='gallery'&&<label>Image description<textarea required rows={2} maxLength={250} value={draft.alt} onChange={e=>update('alt',e.target.value)}/><small>Describe the photo for visitors using screen readers.</small></label>}
    {kind==='tiktok'&&<label>TikTok video URL<input required type="url" placeholder="https://www.tiktok.com/@name/video/123…" value={draft.url} onChange={e=>update('url',e.target.value)}/><small>Open the TikTok video and copy its full browser address. Short share links need to be expanded in your browser first.</small></label>}
    {kind==='testimonials'&&<><label>Client review<textarea required rows={4} maxLength={1500} value={draft.quote} onChange={e=>update('quote',e.target.value)}/></label><div className="form-row"><label>Service <span className="optional">(optional)</span><input maxLength={160} value={draft.service} onChange={e=>update('service',e.target.value)}/></label><label>Rating<select value={draft.rating} onChange={e=>update('rating',+e.target.value)}>{[5,4,3,2,1].map(x=><option key={x} value={x}>{x} stars</option>)}</select></label></div><p className="field-note">Publish real reviews shared by your clients.</p></>}
    <div className="form-row"><label>Display order<input type="number" min={0} max={9999} required value={draft.order} onChange={e=>update('order',Number(e.target.value))}/><small>Lower numbers appear first.</small></label><label className="checkbox-label"><input type="checkbox" checked={draft.visible} onChange={e=>update('visible',e.target.checked)}/> Published on website</label></div><ErrorBox message={error}/><div className="modal-actions"><button type="button" className="button button-outline" onClick={onClose} disabled={busy||uploading}>Cancel</button><button className="button" disabled={busy||uploading}>{busy?'Saving…':uploading?'Uploading photo…':`Save ${labels[kind]}`}</button></div></form></Modal>;
}
function Enquiries(){
  const [items,setItems]=useState<Enquiry[]>([]),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[deleting,setDeleting]=useState<Enquiry|null>(null);
  async function load(){setError('');try{setItems(await api<Enquiry[]>('/admin/enquiries'));}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function status(item:Enquiry,value:string){setBusy(item.id);setError('');try{await api(`/admin/enquiries/${item.id}`,{method:'PATCH',body:JSON.stringify({status:value})});setItems(old=>old.map(x=>x.id===item.id?{...x,status:value}:x));}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
  async function remove(){if(!deleting)return;setBusy(deleting.id);try{await api(`/admin/enquiries/${deleting.id}`,{method:'DELETE'});setItems(old=>old.filter(x=>x.id!==deleting.id));setDeleting(null);}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
  const shown=items.filter(x=>filter==='all'||x.status===filter);
  return <><PageHeading eyebrow="THE STUDIO INBOX" title="Every beautiful visit starts here." description="Reply to clients by phone, then update the status of their enquiry."><button className="button button-outline" onClick={load}><RefreshCw size={17}/> Refresh inbox</button></PageHeading><ErrorBox message={error}/><label className="inbox-filter">Show enquiries<select value={filter} onChange={e=>setFilter(e.target.value)}>{['all','new','contacted','confirmed','completed','cancelled'].map(x=><option key={x} value={x}>{x==='all'?'All enquiries':x}</option>)}</select></label>{loading?<p>Loading enquiries…</p>:shown.length?<div className="enquiry-list">{shown.map(item=><article className="admin-panel enquiry-card" key={item.id}><div className="enquiry-top"><div><span className="eyebrow">{new Date(item.created_at).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</span><h2>{item.name}</h2><p>{item.subject}</p></div><select aria-label={`Status for ${item.name}`} value={item.status} disabled={busy===item.id} onChange={e=>status(item,e.target.value)}>{['new','contacted','confirmed','completed','cancelled'].map(x=><option key={x}>{x}</option>)}</select></div>{item.message&&<p className="enquiry-message">{item.message}</p>}<div className="enquiry-bottom"><a href={`tel:${item.phone.replace(/[^\d+]/g,'')}`}><Phone size={16}/>{item.phone}</a><span>{item.preferred_date?`Preferred date: ${item.preferred_date}`:'No date preference'}</span><button className="icon-button danger-icon" aria-label={`Delete enquiry from ${item.name}`} onClick={()=>setDeleting(item)}><Trash2 size={17}/></button></div></article>)}</div>:<Empty title="You’re all caught up" description="Appointment and academy enquiries from the website will appear here."/>}{deleting&&<Modal title="Delete this enquiry?" onClose={()=>setDeleting(null)}><p>The contact details and message from {deleting.name} will be permanently removed.</p><ErrorBox message={error}/><div className="modal-actions"><button className="button button-outline" onClick={()=>setDeleting(null)}>Keep enquiry</button><button className="button button-danger" onClick={remove} disabled={!!busy}>Delete permanently</button></div></Modal>}</>;
}
function SettingsPage(){
  const [draft,setDraft]=useState<Settings|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploadCount,setUploadCount]=useState(0),[notice,setNotice]=useState('');
  useEffect(()=>{api<Settings>('/admin/settings').then(setDraft).catch(e=>setError(errorMessage(e)));},[]);
  const update=(key:keyof Settings,value:unknown)=>{setDraft(old=>old?{...old,[key]:value}:old);setNotice('');};
  const field=(key:keyof Settings,label:string,required=true,multiline=false)=><label>{label}{multiline?<textarea rows={4} required={required} value={String(draft?.[key]||'')} onChange={e=>update(key,e.target.value)}/>:<input required={required} value={String(draft?.[key]||'')} onChange={e=>update(key,e.target.value)}/>}</label>;
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/admin/settings',{method:'PUT',body:JSON.stringify(draft)});setNotice('Your studio details have been saved.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <><PageHeading eyebrow="MAKE IT PERSONAL" title="The details behind your studio." description="Your story, your photographs, and the best ways for clients to find you."/><ErrorBox message={error}/>{notice&&<div className="notice" role="status"><Check size={17}/>{notice}</div>}{draft&&<form className="settings-form form-stack" onSubmit={submit}><section className="admin-panel settings-panel"><h2>Studio essentials</h2><div className="form-row">{field('name','Business name')}{field('owner','Owner')}</div><div className="form-row">{field('phone','Display phone number')}{field('internationalPhone','International phone number')}</div>{field('address','Address')}<label className="checkbox-label"><input type="checkbox" checked={draft.whatsappEnabled} onChange={e=>update('whatsappEnabled',e.target.checked)}/> This phone number is available on WhatsApp</label></section><section className="admin-panel settings-panel"><h2>Your first impression</h2>{field('heroTitle','Homepage headline')}{field('heroDescription','Homepage introduction',true,true)}<div className="form-row"><ImageField label="Hero photograph" value={draft.heroImage} onChange={v=>update('heroImage',v)} onBusy={v=>setUploadCount(n=>n+(v?1:-1))}/><ImageField label="Makeup feature photograph" value={draft.featureImage} onChange={v=>update('featureImage',v)} onBusy={v=>setUploadCount(n=>n+(v?1:-1))}/></div></section><section className="admin-panel settings-panel"><h2>Meet the founder</h2>{field('about','Your story',true,true)}<ImageField label="Owner portrait (optional)" value={draft.ownerImage} onChange={v=>update('ownerImage',v)} onBusy={v=>setUploadCount(n=>n+(v?1:-1))}/></section><section className="admin-panel settings-panel"><h2>Social profiles & directions</h2><p>Leave a link empty to keep it off the website.</p><div className="form-row">{field('instagram','Instagram profile URL',false)}{field('facebook','Facebook page URL',false)}</div><div className="form-row">{field('tiktok','TikTok profile URL',false)}{field('mapsUrl','Google Maps listing URL',false)}</div></section><ErrorBox message={error}/><div className="settings-save"><button className="button" disabled={busy||uploadCount>0}>{busy?'Saving…':uploadCount>0?'Uploading images…':'Save studio settings'}</button></div></form>}</>;
}
function Account(){
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const node=e.currentTarget,form=new FormData(node);setError('');setNotice('');if(form.get('new')!==form.get('confirm')){setError('The new passwords do not match.');return;}setBusy(true);try{await api('/admin/password',{method:'POST',body:JSON.stringify({currentPassword:form.get('current'),newPassword:form.get('new')})});setNotice('Password updated. Other sessions have been signed out.');node.reset();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <><PageHeading eyebrow="YOUR ACCOUNT" title="Keep your studio secure." description="Choose a long, unique password that you keep just for this website."/><form className="admin-panel settings-panel form-stack account-form" onSubmit={submit}><h2>Change your password</h2><label>Current password<input name="current" type="password" required autoComplete="current-password"/></label><label>New password<input name="new" type="password" required minLength={12} maxLength={200} autoComplete="new-password"/><small>At least 12 characters.</small></label><label>Confirm new password<input name="confirm" type="password" required minLength={12} maxLength={200} autoComplete="new-password"/></label><ErrorBox message={error}/>{notice&&<div className="notice" role="status">{notice}</div>}<button className="button" disabled={busy}>{busy?'Updating…':'Update password'}</button></form></>;
}
