import { useEffect, useState, type FormEvent } from 'react';
import { Menu, X, Phone, MapPin, Instagram, Facebook, Play, Check, ChevronLeft, ChevronRight, GraduationCap, Heart, Star, MessageCircle, Sparkles } from 'lucide-react';
import { api, errorMessage } from './api';
import { Brand, Icon, Modal, Empty, ErrorBox } from './components';
import type { Content, SiteData } from './types';
import { registerPublicTools } from './webmcp';

type Booking = {serviceId?:string;courseId?:string};
export function PublicSite() {
  const [data,setData]=useState<SiteData|null>(null),[error,setError]=useState(''),[menu,setMenu]=useState(false);
  const [category,setCategory]=useState('All'),[expanded,setExpanded]=useState(false),[booking,setBooking]=useState<Booking|null>(null);
  const [lightbox,setLightbox]=useState<number|null>(null),[playing,setPlaying]=useState<string[]>([]);
  useEffect(()=>{api<SiteData>('/site').then(setData).catch(e=>setError(errorMessage(e)));},[]);
  useEffect(registerPublicTools,[]);
  useEffect(()=>{
    if(!data || lightbox===null) return;
    const move=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')setLightbox(i=>i===null?null:(i+1)%data.gallery.length);if(e.key==='ArrowLeft')setLightbox(i=>i===null?null:(i-1+data.gallery.length)%data.gallery.length);};
    window.addEventListener('keydown',move);return()=>window.removeEventListener('keydown',move);
  },[data,lightbox]);
  if(error)return <div className="page-loading"><Brand/><ErrorBox message={error}/><button className="button" onClick={()=>location.reload()}>Try again</button><a href="tel:+9779804902596">Call the studio</a></div>;
  if(!data)return <div className="page-loading"><Brand/><span className="loading-line"/><p>Welcome to your little moment of beauty.</p></div>;
  const {settings:s,services,courses,gallery,tiktok,testimonials}=data;
  const filtered=services.filter(x=>category==='All'||x.category===category);
  const shown=expanded?filtered:filtered.slice(0,6);
  const maps=s.mapsUrl || `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.address)}`;
  const categories=['All',...new Set(services.map(x=>x.category).filter(Boolean))];
  const navigate=()=>setMenu(false);
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <div className="top-note"><span>YOUR BEAUTY. YOUR CONFIDENCE. YOUR MOMENT.</span><a href={maps} target="_blank" rel="noreferrer"><MapPin size={13}/> Dhulabari, Nepal</a></div>
    <header className="site-header"><div className="nav-wrap"><Brand/><nav className={menu?'nav-links is-open':'nav-links'} aria-label="Main navigation">
      {['Home','Services','Academy','Gallery','TikTok','About','Contact'].map(item=><a key={item} href={`#${item.toLowerCase()}`} onClick={navigate}>{item}</a>)}
    </nav><button className="button nav-book" onClick={()=>setBooking({})}>Book appointment</button><button className="icon-button mobile-menu" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
    <main id="main">
      <section id="home" className="hero section-shell"><div className="hero-copy"><p className="eyebrow"><span/> A BEAUTIFUL KIND OF YOU</p><h1>{s.heroTitle === 'Beauty, styled your way.' ? <>Beauty, styled<br/><em>your way.</em></>:s.heroTitle}</h1><p className="hero-description">{s.heroDescription}</p><div className="hero-buttons"><button className="button" onClick={()=>setBooking({})}>Book an appointment</button><a className="text-link" href="#services">Explore our services</a></div><div className="hero-footnote"><span className="mini-icon"><Heart size={18} strokeWidth={1.4}/></span><div>Made for your everyday.<br/><strong>And your unforgettable days.</strong></div></div></div>
      <div className="hero-visual"><div className="hero-image-frame"><img src={s.heroImage || '/images/hero.webp'} alt="Editorial beauty inspiration with soft rose makeup and an elegant hairstyle" fetchPriority="high"/><span className="vertical-caption">THE ART OF FEELING BEAUTIFUL</span></div><div className="hero-tag"><Sparkles size={25} strokeWidth={1}/><span>A little glow.<br/><em>A lot of you.</em></span></div><span className="image-caption">Beauty inspiration · campaign imagery</span></div></section>
      <div className="service-ribbon" aria-label="Studio specialties">{['MAKEUP','HAIR','NAILS','SKIN','MEHENDI','ACADEMY'].map((x,i)=><span key={x}>{i>0&&<span className="ribbon-star">✧</span>}{x}</span>)}</div>
      <section className="section-shell services-section" id="services"><div className="section-heading"><div><p className="eyebrow">THE STUDIO MENU</p><h2>A little care.<br/><em>A beautiful difference.</em></h2></div><p>From a fresh everyday look to your biggest celebration, find something just for you.</p></div>
      <div className="filter-tabs" aria-label="Filter services">{categories.map(cat=><button key={cat} className={category===cat?'active':''} onClick={()=>{setCategory(cat!);setExpanded(false);}} aria-pressed={category===cat}>{cat}</button>)}</div>
      {services.length ? <><div className="services-grid">{shown.map((item,i)=><article className="service-card" key={item.id}><div className="service-card-top">{item.image?<img className="service-thumb" src={item.image} alt="" loading="lazy"/>:<Icon name={item.icon}/>}<span>0{i+1}</span></div><h3>{item.title}</h3><p>{item.description}</p><div className="service-card-bottom"><span>{item.price || 'Let’s find your look'}{item.duration && ` · ${item.duration}`}</span><button className="round-link" aria-label={`Enquire about ${item.title}`} onClick={()=>setBooking({serviceId:item.id})}><span>+</span></button></div></article>)}</div>{filtered.length>6&&<button className="button button-outline centered" onClick={()=>setExpanded(!expanded)}>{expanded?'Show fewer services':`Explore all ${filtered.length} services`}</button>}</>:<Empty title="Let’s talk beauty" description="Call us to explore the services available at the studio."/>}</section>
      <section className="occasion-section"><div className="section-shell occasion-inner"><div className="occasion-photo"><img src={s.featureImage||'/images/still-life.webp'} alt="Rose makeup and brushes arranged on warm ivory stone" loading="lazy"/><span className="photo-label">THE FINISHING TOUCH</span></div><div className="occasion-copy"><p className="eyebrow">FOR THE MOMENTS THAT MATTER</p><h2>Your day.<br/>Your look.<br/><em>Your kind of beautiful.</em></h2><p>From soft bridal radiance to expressive occasion makeup, let’s create a look that feels as special as the moment.</p><div className="occasion-tags"><span>Bridal</span><span>Party</span><span>Special occasions</span></div><button className="button" onClick={()=>setBooking({serviceId:services.find(x=>x.title==='Bridal Makeup')?.id})}>Book your makeup</button></div></div></section>
      <section className="section-shell academy-section" id="academy"><div className="academy-intro"><span className="academy-badge"><GraduationCap size={22}/> THE CHOOSE ME ACADEMY</span><h2>Learn. Create.<br/><em>Become a professional.</em></h2><p>Turn your love for beauty into skills you can build on. Practical learning, creative exploration and room to discover your own style.</p><div className="certificate"><Check size={18}/> Certificates after successful course completion</div><button className="button" onClick={()=>setBooking({courseId:courses[0]?.id})}>Enquire about courses</button></div><div className="course-list">{courses.map((course,i)=><button className="course-row" key={course.id} onClick={()=>setBooking({courseId:course.id})}><span className="course-number">0{i+1}</span><span><h3>{course.title}</h3><p>{course.description}</p>{course.duration&&<small>{course.duration}</small>}</span><span className="course-plus">+</span></button>)}{!courses.length&&<Empty title="Your creative journey starts here" description="Contact the studio for upcoming training opportunities."/>}</div></section>
      <section className="social-section" id="tiktok"><div className="section-shell"><div className="section-heading"><div><p className="eyebrow">A LITTLE BEHIND THE BEAUTY</p><h2>See our <em>latest looks.</em></h2></div><p>Makeup transformations, hairstyles, bridal looks and the little details in between.</p></div>
      {tiktok.length ? <div className="video-grid">{tiktok.map(video=>{const id=video.url?.match(/\/video\/(\d+)/)?.[1];return <article className="video-card" key={video.id}>{playing.includes(video.id)?<iframe src={`https://www.tiktok.com/player/v1/${id}?autoplay=0`} title={video.title} allow="fullscreen" allowFullScreen loading="lazy"/>:<button className="video-poster" onClick={()=>setPlaying([...playing,video.id])}><span className="play-circle"><Play size={30}/></span><h3>{video.title}</h3><span>Play on TikTok</span><small>Loads content from TikTok</small></button>}<a href={video.url} target="_blank" rel="noreferrer">Open on TikTok</a></article>;})}</div>:<div className="social-empty"><span className="play-circle"><Play size={26}/></span><div><h3>A closer look, coming soon.</h3><p>Our latest studio videos will appear here. For now, let’s talk about your next look.</p></div><button className="button button-outline" onClick={()=>setBooking({})}>Connect with the studio</button></div>}
      {s.tiktok&&<a className="text-link centered" href={s.tiktok} target="_blank" rel="noreferrer">Follow us on TikTok</a>}</div></section>
      <section className="section-shell gallery-section" id="gallery"><div className="section-heading"><div><p className="eyebrow">DETAILS WE LOVE</p><h2>The beauty <em>of our work.</em></h2></div><p>Real moments. Thoughtful details. A little inspiration for your next visit.</p></div>{gallery.length?<div className="gallery-grid">{gallery.map((photo,i)=><button className="gallery-photo" key={photo.id} onClick={()=>setLightbox(i)} aria-label={`View ${photo.title}`}><img src={photo.image} alt={photo.alt} loading="lazy"/><span>{photo.title}<small>{photo.category}</small></span></button>)}</div>:<div className="gallery-empty"><div><span className="eyebrow">THE PORTFOLIO</span><h3>Beautiful moments,<br/><em>worth sharing.</em></h3><p>Our studio portfolio is being curated. Enquire about a look you have in mind.</p><button className="text-link" onClick={()=>setBooking({})}>Let’s create your look</button></div><div className="gallery-inspiration"><img src={s.featureImage||'/images/still-life.webp'} alt="Decorative beauty still life" loading="lazy"/><span>Editorial inspiration</span></div></div>}</section>
      <section className="about-section" id="about"><div className="section-shell about-inner">{s.ownerImage?<img className="owner-photo" src={s.ownerImage} alt={s.owner} loading="lazy"/>:<div className="owner-monogram" aria-hidden="true"><span>r.</span><small>A NOTE FROM THE FOUNDER</small></div>}<div className="about-copy"><p className="eyebrow">THE HEART BEHIND CHOOSE ME</p><h2>Meet <em>{s.owner.split(' ')[0]}.</em></h2><p>{s.about}</p><div className="signature">{s.owner}<small>FOUNDER · CHOOSE ME</small></div></div></div></section>
      {testimonials.length>0&&<section className="section-shell review-section"><p className="eyebrow">KIND WORDS</p><h2>A little love <em>from our clients.</em></h2><div className="reviews-grid">{testimonials.map(review=><figure className="review" key={review.id}><div aria-label={`${review.rating} out of 5 stars`} className="stars">{Array.from({length:review.rating||5},(_,i)=><Star size={15} fill="currentColor" key={i}/>)}</div><blockquote>“{review.quote}”</blockquote><figcaption>{review.title}<span>{review.service}</span></figcaption></figure>)}</div></section>}
      <section className="booking-banner section-shell"><span className="eyebrow">MAKE TIME FOR YOU</span><h2>Ready for <em>your next look?</em></h2><p>Your next little moment of confidence starts here.</p><div><button className="button" onClick={()=>setBooking({})}>Book an appointment</button><a className="button button-outline" href={`tel:${s.internationalPhone}`}><Phone size={17}/> Call {s.phone}</a></div></section>
      <section className="section-shell contact-section" id="contact"><div><p className="eyebrow">COME SAY HELLO</p><h2>Your beauty destination,<br/><em>right here in Dhulabari.</em></h2></div><div className="contact-details"><div><MapPin size={22}/><span><strong>Find the studio</strong>{s.address}<a href={maps} className="text-link" target="_blank" rel="noreferrer">Get directions</a></span></div><div><Phone size={21}/><span><strong>Let’s talk</strong><a href={`tel:${s.internationalPhone}`}>{s.phone}</a><small>Please call for opening hours and availability.</small></span></div>{s.whatsappEnabled&&<a className="text-link" href={`https://wa.me/${s.internationalPhone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Chat on WhatsApp</a>}</div></section>
    </main>
    <footer className="site-footer"><div className="section-shell footer-main"><div><Brand light/><p>A little care. A little confidence.<br/>A beautiful kind of you.</p></div><div className="footer-links">{['Services','Academy','Gallery','TikTok','Contact'].map(x=><a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</div><div className="footer-address"><p>{s.owner}<br/>{s.address}</p><a href={`tel:${s.internationalPhone}`}>{s.phone}</a><div className="social-links">{s.instagram&&<a href={s.instagram} aria-label="Instagram" target="_blank" rel="noreferrer"><Instagram size={20}/></a>}{s.facebook&&<a href={s.facebook} aria-label="Facebook" target="_blank" rel="noreferrer"><Facebook size={20}/></a>}{s.tiktok&&<a href={s.tiktok} target="_blank" rel="noreferrer">TikTok</a>}</div></div></div><div className="section-shell footer-bottom"><span>© {new Date().getFullYear()} {s.name}. All rights reserved.</span><a href="/admin">Studio login</a></div></footer>
    <div className="mobile-booking"><a href={`tel:${s.internationalPhone}`}><Phone size={18}/> Call studio</a><button onClick={()=>setBooking({})}>Book appointment</button></div>
    {booking&&<BookingDialog data={data} selection={booking} onClose={()=>setBooking(null)}/>}
    {lightbox!==null&&gallery[lightbox]&&<Modal title={gallery[lightbox].title} wide onClose={()=>setLightbox(null)}><div className="lightbox"><img src={gallery[lightbox].image} alt={gallery[lightbox].alt}/><div className="lightbox-controls"><button className="icon-button" aria-label="Previous photo" onClick={()=>setLightbox((lightbox-1+gallery.length)%gallery.length)}><ChevronLeft/></button><span>{lightbox+1} / {gallery.length}</span><button className="icon-button" aria-label="Next photo" onClick={()=>setLightbox((lightbox+1)%gallery.length)}><ChevronRight/></button></div></div></Modal>}
  </>;
}

function BookingDialog({data,selection,onClose}:{data:SiteData;selection:Booking;onClose:()=>void}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState('');
  const [selected,setSelected]=useState(selection.courseId ? `course:${selection.courseId}` : selection.serviceId ? `service:${selection.serviceId}` : '');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const [kind,id]=selected.split(':');try{const result=await api<{message:string}>('/enquiries',{method:'POST',body:JSON.stringify({name:form.get('name'),phone:form.get('phone'),message:form.get('message'),website:form.get('website'),preferredDate:form.get('date'),...(kind==='service'?{serviceId:id}:kind==='course'?{courseId:id}:{})})});setDone(result.message);}catch(error){setError(errorMessage(error));}finally{setBusy(false);}}
  return <Modal title={done?'Thank you. We’ll be in touch.':'A little time for you.'} onClose={onClose}>{done?<div className="booking-success"><span className="success-circle"><Check/></span><p>{done}</p><button className="button" onClick={onClose}>Lovely, thank you</button></div>:<form onSubmit={submit} className="form-stack"><p className="form-intro">Tell us what you have in mind. We’ll call you to discuss your visit or course enquiry.</p><div className="form-row"><label>Your name<input name="name" required maxLength={100} autoComplete="name"/></label><label>Phone number<input name="phone" type="tel" required maxLength={25} autoComplete="tel" placeholder="98XXXXXXXX"/></label></div><label>I’m interested in<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Let’s discuss my look</option><optgroup label="Beauty services">{data.services.map(x=><option key={x.id} value={`service:${x.id}`}>{x.title}</option>)}</optgroup><optgroup label="Academy courses">{data.courses.map(x=><option key={x.id} value={`course:${x.id}`}>{x.title}</option>)}</optgroup></select></label><label>Preferred date <span className="optional">(optional)</span><input name="date" type="date" min={new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kathmandu'})}/></label><label>Anything you’d like us to know? <span className="optional">(optional)</span><textarea name="message" rows={3} maxLength={2000}/></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><ErrorBox message={error}/><button className="button" disabled={busy}>{busy?'Sending your enquiry…':'Send enquiry'}</button><small className="form-note">We use these details to respond to your enquiry. Your appointment is confirmed only after we contact you.</small></form>}</Modal>;
}
